# Generated by Django 5.1.5 on 2026-10-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishMarathiMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('marathi_term', models.CharField(db_index=True, max_length=200)),
                ('is_phrase', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'English-Marathi Lexical Mapping',
                'verbose_name_plural': 'English-Marathi Lexical Mappings',
                'ordering': ['english_term'],
            },
        ),
        migrations.CreateModel(
            name='SignVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_id', models.CharField(db_index=True, help_text='Canonical sign identifier (e.g. SIGN_HELLO, SIGN_WATER)', max_length=100, unique=True)),
                ('marathi_term', models.CharField(db_index=True, help_text='Primary Marathi term in Devanagari script', max_length=200)),
                ('english_gloss', models.CharField(db_index=True, help_text='Standard English gloss / equivalent term', max_length=200)),
                ('category', models.CharField(choices=[('greetings', 'Greetings'), ('family', 'Family'), ('pronouns', 'Pronouns'), ('numbers', 'Numbers'), ('time', 'Time'), ('verbs', 'Common Verbs'), ('questions', 'Question Words'), ('objects', 'Everyday Objects'), ('fingerspelling', 'Alphabet / Fingerspelling'), ('other', 'Other')], db_index=True, default='other', max_length=100)),
                ('sign_type', models.CharField(choices=[('lexical', 'Lexical Sign'), ('phrase', 'Phrase Sign'), ('number', 'Numeric Sign'), ('fingerspell', 'Fingerspelling Character')], default='lexical', max_length=50)),
                ('animation_asset', models.CharField(help_text='Relative path to MP4 animation inside MEDIA_ROOT (e.g. animations/greetings/hello.mp4)', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Linguistic/biomechanical metadata (hand shape, motion, two_handed, description)')),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='List of Marathi/English synonyms and alternate representations')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sign is active in the translation engine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sign Vocabulary Entry',
                'verbose_name_plural': 'Sign Vocabulary Entries',
                'ordering': ['category', 'marathi_term'],
            },
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Original raw input text or speech transcript')),
                ('input_language', models.CharField(choices=[('mr', 'Marathi'), ('en', 'English')], default='mr', max_length=10)),
                ('input_mode', models.CharField(choices=[('text', 'Text Input'), ('speech', 'Speech Input')], default='text', max_length=10)),
                ('normalized_text', models.TextField(help_text='Normalized text representation')),
                ('generated_sign_sequence', models.JSONField(default=list, help_text='Ordered list of resolved canonical sign objects')),
                ('fallback_words', models.JSONField(blank=True, default=list, help_text='Words that underwent fingerspelling fallback')),
                ('processing_time_ms', models.FloatField(default=0.0, help_text='Total end-to-end processing time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Translation History',
                'verbose_name_plural': 'Translation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnknownWordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200, unique=True)),
                ('language', models.CharField(default='mr', max_length=10)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unknown Word Log',
                'verbose_name_plural': 'Unknown Word Logs',
                'ordering': ['-occurrence_count', '-last_seen'],
            },
        ),
    ]
